function [inputFeatures, forbiddenFeatures] = select_clustering_features()
%SELECT_CLUSTERING_FEATURES Explicit Phase 5 clustering input list.
%
% Scenario labels, traffic mode, impairment flags, power offsets, and direct
% fault/status labels are intentionally excluded from this list.

inputFeatures = {'attached_ue_count','active_ue_count', ...
    'offered_traffic_Mbps','served_traffic_Mbps','unserved_traffic_Mbps', ...
    'sector_capacity_Mbps','sector_load_ratio','mean_RSRP_dBm','median_RSRP_dBm', ...
    'mean_SINR_dB','median_SINR_dB','mean_UE_throughput_Mbps', ...
    'median_UE_throughput_Mbps','qos_satisfaction_ratio','boundary_ue_ratio', ...
    'handover_risk_score','attach_rate_sector'};

forbiddenFeatures = {'scenario_id','scenario_name','scenario_label','traffic_mode', ...
    'sector_status','impaired_sector_id','impaired_site_id','impaired_sector_status', ...
    'is_impaired_sector','referencePowerOffset_dB','txPowerOffset_dB', ...
    'overload_flag','es_candidate','cod_label','outage_flag','degradation_flag', ...
    'outage_label','degraded_label'};
end
