function actions = empty_action_table()
%EMPTY_ACTION_TABLE Shared schema for Phase 8A candidate actions.

actions = table('Size', [0 28], ...
    'VariableTypes', {'double','double','double','cell','double','double','double','double', ...
    'double','double','double','double','double','double','double','double','double','double', ...
    'cell','cell','double','double','double','double','double','double','double','cell'}, ...
    'VariableNames', {'dataset_id','scenario_id','realization_id','scenario_name','source_site_id', ...
    'source_sector_id','target_sector_id','impaired_sector_id','source_load_ratio', ...
    'source_mean_RSRP_dBm','source_mean_SINR_dB','source_qos_satisfaction_ratio', ...
    'source_handover_risk_score','source_attach_rate_sector','cluster_id','cod_score_normal', ...
    'cod_score_degraded','cod_score_outage','module_name','action_type','delta_prs_dB', ...
    'delta_tilt_deg','delta_cio_dB','delta_hom_dB','delta_ttt_ms','sleep_flag', ...
    'is_no_op','notes'});
end
