function [selectedFinal, regretTable, comparisonTable] = evaluate_safety_enforced_selection(selectionTable, joinedTable, oracleTable)
%EVALUATE_SAFETY_ENFORCED_SELECTION Attach oracle reference and regret.
%
% Joins selectionTable (per group) with the oracle table (per group) and
% computes:
%   raw_regret             = oracle_reward - raw_true_reward
%   safety_enforced_regret = oracle_reward - safe_true_reward
%   raw_top1_oracle_match  = (raw selected action_id == oracle action_id)
%   safe_top1_oracle_match = (safe selected action_id == oracle action_id)
%   safe_top2_oracle_match = oracle action_id is in top-2 safe-ranked
%
% True reward = actual_reward column from Phase 9B predictions (= reward
% column from Phase 8B). Predicted reward is used only to choose the ML
% action; it is never substituted for actual reward in regret calculation.

if isempty(selectionTable)
    selectedFinal = selectionTable;
    regretTable = build_empty_regret();
    comparisonTable = build_empty_comparison();
    return;
end

oracleKey = oracleTable.oracle_group_id;
[match, loc] = ismember(selectionTable.oracle_group_id, oracleKey);
if ~all(match)
    missing = selectionTable.oracle_group_id(~match);
    error('Phase 10A: %d decision groups have no Phase 8C oracle row (e.g. %d).', ...
        sum(~match), missing(1));
end
oracleRows = oracleTable(loc, :);

oracleActionId = oracleRows.selected_action_id;
oracleReward = oracleRows.reward;

rawRegret = oracleReward - selectionTable.raw_true_reward;
safetyRegret = oracleReward - selectionTable.safe_true_reward;
rawMatch = double(selectionTable.selected_action_id_raw == oracleActionId);
safeMatch = double(selectionTable.selected_action_id_safe == oracleActionId);

safeTop2Match = zeros(height(selectionTable), 1);
T = joinedTable;
T.module_name = string(T.module_name);
T.action_type = string(T.action_type);
isFunctionalNoOp = logical(T.is_no_op) | ...
    (T.module_name == "ES" & T.action_type == "keep_active");
[uniqueGroups, ~, idx] = unique(T.oracle_group_id, 'stable');
for g = 1:numel(uniqueGroups)
    selRow = find(selectionTable.oracle_group_id == uniqueGroups(g), 1, 'first');
    if isempty(selRow)
        continue;
    end
    grpRows = T(idx == g, :);
    safeMask = ~logical(grpRows.safety_is_unsafe);
    if any(safeMask)
        safeRows = grpRows(safeMask, :);
    else
        noopMask = isFunctionalNoOp(idx == g);
        if any(noopMask)
            safeRows = grpRows(noopMask, :);
        else
            safeRows = grpRows;
        end
    end
    [~, ord] = sort(safeRows.predicted_reward, 'descend');
    safeRows = safeRows(ord, :);
    if height(safeRows) >= 2
        topIds = safeRows.action_id(1:2);
    else
        topIds = safeRows.action_id(1);
    end
    safeTop2Match(selRow) = double(any(topIds == oracleActionId(selRow)));
end

selectedFinal = selectionTable;
selectedFinal.oracle_action_id = oracleActionId;
selectedFinal.oracle_reward = oracleReward;
selectedFinal.raw_regret = rawRegret;
selectedFinal.safety_enforced_regret = safetyRegret;
selectedFinal.raw_top1_oracle_match = rawMatch;
selectedFinal.safe_top1_oracle_match = safeMatch;
selectedFinal.safe_top2_oracle_match = safeTop2Match;
selectedFinal.raw_action_id_for_top2 = [];
selectedFinal.safe_action_id_for_top2 = [];

selectedFinal = movevars(selectedFinal, ...
    {'oracle_action_id','oracle_reward','raw_regret','safety_enforced_regret', ...
    'raw_top1_oracle_match','safe_top1_oracle_match','safe_top2_oracle_match'}, ...
    'After', 'es_action');

regretTable = table(selectedFinal.oracle_group_id, selectedFinal.module_name, ...
    selectedFinal.scenario_name, selectedFinal.realization_id, ...
    selectedFinal.source_sector_id, selectedFinal.oracle_reward, ...
    selectedFinal.raw_true_reward, selectedFinal.safe_true_reward, ...
    selectedFinal.raw_regret, selectedFinal.safety_enforced_regret, ...
    selectedFinal.raw_top1_oracle_match, selectedFinal.safe_top1_oracle_match, ...
    selectedFinal.safe_top2_oracle_match, ...
    'VariableNames', {'oracle_group_id','module_name','scenario_name', ...
    'realization_id','source_sector_id','oracle_reward','raw_true_reward', ...
    'safe_true_reward','raw_regret','safety_enforced_regret', ...
    'raw_top1_oracle_match','safe_top1_oracle_match','safe_top2_oracle_match'});

comparisonTable = table(selectedFinal.oracle_group_id, selectedFinal.module_name, ...
    selectedFinal.scenario_name, selectedFinal.realization_id, ...
    selectedFinal.source_sector_id, selectedFinal.selected_action_id_raw, ...
    selectedFinal.selected_action_id_safe, selectedFinal.oracle_action_id, ...
    selectedFinal.raw_predicted_reward, selectedFinal.safe_predicted_reward, ...
    selectedFinal.raw_true_reward, selectedFinal.safe_true_reward, ...
    selectedFinal.oracle_reward, selectedFinal.raw_selected_safety_valid, ...
    selectedFinal.safe_selected_safety_valid, selectedFinal.safety_filter_changed_action, ...
    selectedFinal.fallback_used, selectedFinal.noop_selected, ...
    selectedFinal.selection_reason, selectedFinal.raw_regret, ...
    selectedFinal.safety_enforced_regret, selectedFinal.raw_top1_oracle_match, ...
    selectedFinal.safe_top1_oracle_match, selectedFinal.safe_top2_oracle_match, ...
    'VariableNames', {'oracle_group_id','module_name','scenario_name','realization_id', ...
    'source_sector_id','selected_action_id_raw','selected_action_id_safe', ...
    'oracle_action_id','raw_predicted_reward','safe_predicted_reward', ...
    'raw_true_reward','safe_true_reward','oracle_reward', ...
    'raw_selected_safety_valid','safe_selected_safety_valid', ...
    'safety_filter_changed_action','fallback_used','noop_selected', ...
    'selection_reason','raw_regret','safety_enforced_regret', ...
    'raw_top1_oracle_match','safe_top1_oracle_match','safe_top2_oracle_match'});
end

function T = build_empty_regret()
T = table('Size', [0 13], ...
    'VariableTypes', {'double','cell','cell','double','double','double','double','double','double','double','double','double','double'}, ...
    'VariableNames', {'oracle_group_id','module_name','scenario_name','realization_id','source_sector_id', ...
    'oracle_reward','raw_true_reward','safe_true_reward','raw_regret','safety_enforced_regret', ...
    'raw_top1_oracle_match','safe_top1_oracle_match','safe_top2_oracle_match'});
end

function T = build_empty_comparison()
T = table('Size', [0 24], ...
    'VariableTypes', {'double','cell','cell','double','double','double','double','double','double','double','double','double','double','logical','logical','logical','logical','logical','cell','double','double','double','double','double'}, ...
    'VariableNames', {'oracle_group_id','module_name','scenario_name','realization_id','source_sector_id', ...
    'selected_action_id_raw','selected_action_id_safe','oracle_action_id','raw_predicted_reward', ...
    'safe_predicted_reward','raw_true_reward','safe_true_reward','oracle_reward', ...
    'raw_selected_safety_valid','safe_selected_safety_valid','safety_filter_changed_action', ...
    'fallback_used','noop_selected','selection_reason','raw_regret','safety_enforced_regret', ...
    'raw_top1_oracle_match','safe_top1_oracle_match','safe_top2_oracle_match'});
end
