function finalDecisions = build_final_coordinator_decisions(inputTable, candidateActions, rejectedLog, resolutionLog)
%BUILD_FINAL_COORDINATOR_DECISIONS Assemble the Phase 11B decision table.
%
% Joins Phase 11A inputs with candidate accept/reject flags, attaches
% rejection metadata (conflict_id, conflict_type, rejected_by_module),
% classifies each row into a final_decision_status, and writes the
% executable_flag + not_applied_flag with the strict rule that unsafe
% fallback rows are NEVER executable.

if isempty(inputTable)
    finalDecisions = build_empty_table();
    return;
end

% Align candidate rows with input rows by action_id (1:1 by construction).
[match, loc] = ismember(inputTable.selected_action_id_safe, candidateActions.accepted_action_id);
if ~all(match)
    error('Phase 11B: every input action_id must appear in candidate table.');
end
cand = candidateActions(loc, :);

% Rejection metadata, joined on rejected_action_id.
rejConflictId = nan(height(inputTable), 1);
rejConflictType = strings(height(inputTable), 1);
rejSafetyFlag = false(height(inputTable), 1);
if ~isempty(rejectedLog) && height(rejectedLog) > 0
    [m, l] = ismember(inputTable.selected_action_id_safe, rejectedLog.rejected_action_id);
    matchedIdx = find(m);
    rejConflictId(matchedIdx) = rejectedLog.conflict_id(l(matchedIdx));
    rejConflictType(matchedIdx) = string(rejectedLog.rejection_type(l(matchedIdx)));
    rejSafetyFlag(matchedIdx) = logical(rejectedLog.safety_related_flag(l(matchedIdx)));
end

% Classify each row.
[statusCol, executableCol, unresolvedFlag] = classify_final_action_status( ...
    cand.accepted_flag, cand.rejected_flag, inputTable.noop_selected, ...
    inputTable.fallback_used, inputTable.safe_selected_safety_valid, ...
    rejConflictType, rejSafetyFlag);

% Final decision rank: within each coordinator_group_id, rank executable
% rows by module_priority ascending. Non-executable rows get rank 0.
finalRank = zeros(height(inputTable), 1);
[~, ~, gIdx] = unique(inputTable.coordinator_group_id, 'stable');
for g = unique(gIdx)'
    members = find(gIdx == g & executableCol);
    if isempty(members), continue; end
    [~, ord] = sort(inputTable.module_priority(members), 'ascend');
    finalRank(members(ord)) = 1:numel(members);
end

finalDecisionId = (1:height(inputTable))';

% Compose output.
finalDecisions = table( ...
    finalDecisionId, ...
    inputTable.coordinator_group_id, inputTable.scenario_name, inputTable.realization_id, ...
    inputTable.module_name, inputTable.module_priority, ...
    inputTable.decision_source_sector_id, inputTable.decision_target_sector_id, ...
    inputTable.source_sector_id, inputTable.target_sector_id, ...
    inputTable.coordinator_affected_sector_id, inputTable.application_affected_sector_id, ...
    inputTable.application_state_variable, inputTable.affected_sector_id, inputTable.affected_parameter, ...
    inputTable.selected_action_id_safe, inputTable.safe_action_type, ...
    cellstr(statusCol), executableCol, true(height(inputTable), 1), ...
    inputTable.safe_selected_safety_valid, inputTable.fallback_used, ...
    inputTable.noop_selected, unresolvedFlag, ...
    cellstr(rejConflictType), rejConflictId, cellstr(rejConflictType), ...
    finalRank, ...
    inputTable.predicted_reward, inputTable.true_reward, ...
    inputTable.safety_enforced_regret, ...
    inputTable.delta_prs_dB, inputTable.delta_tilt_deg, inputTable.delta_cio_dB, ...
    inputTable.delta_hom_dB, inputTable.delta_ttt_ms, inputTable.es_action, ...
    'VariableNames', {'final_decision_id','coordinator_group_id','scenario_name', ...
    'realization_id','module_name','module_priority', ...
    'decision_source_sector_id','decision_target_sector_id', ...
    'source_sector_id','target_sector_id', ...
    'coordinator_affected_sector_id','application_affected_sector_id', ...
    'application_state_variable','affected_sector_id','affected_parameter', ...
    'selected_action_id_safe','accepted_action_type', ...
    'final_decision_status','executable_flag','not_applied_flag', ...
    'safety_valid','fallback_used','noop_selected','unresolved_fallback_flag', ...
    'rejection_reason','conflict_id','conflict_type','final_candidate_rank', ...
    'predicted_reward','true_reward','safety_enforced_regret', ...
    'delta_prs_dB','delta_tilt_deg','delta_cio_dB','delta_hom_dB','delta_ttt_ms','es_action'});

% Resolution-log decoration: if a rejected row has a known resolution row,
% use its winning module / reason instead of the raw rejection_type for
% the human-readable rejection_reason column.
if ~isempty(resolutionLog) && height(resolutionLog) > 0
    rejMask = strcmp(finalDecisions.final_decision_status, 'rejected_priority_conflict') | ...
        strcmp(finalDecisions.final_decision_status, 'rejected_safety_conflict');
    for r = find(rejMask)'
        actionId = finalDecisions.selected_action_id_safe(r);
        loc = find(resolutionLog.rejected_action_id == actionId, 1);
        if isempty(loc), continue; end
        finalDecisions.rejection_reason{r} = resolutionLog.resolution_reason{loc};
        finalDecisions.conflict_id(r) = resolutionLog.conflict_id(loc);
    end
end
end

function T = build_empty_table()
T = table('Size', [0 37], ...
    'VariableTypes', {'double','double','cell','double','cell','double', ...
    'double','double','double','double','double','double','cell','double','cell','double','cell', ...
    'cell','logical','logical','logical','logical','logical','logical', ...
    'cell','double','cell','double', ...
    'double','double','double', ...
    'double','double','double','double','double','cell'}, ...
    'VariableNames', {'final_decision_id','coordinator_group_id','scenario_name', ...
    'realization_id','module_name','module_priority', ...
    'decision_source_sector_id','decision_target_sector_id', ...
    'source_sector_id','target_sector_id', ...
    'coordinator_affected_sector_id','application_affected_sector_id', ...
    'application_state_variable','affected_sector_id','affected_parameter', ...
    'selected_action_id_safe','accepted_action_type', ...
    'final_decision_status','executable_flag','not_applied_flag', ...
    'safety_valid','fallback_used','noop_selected','unresolved_fallback_flag', ...
    'rejection_reason','conflict_id','conflict_type','final_candidate_rank', ...
    'predicted_reward','true_reward','safety_enforced_regret', ...
    'delta_prs_dB','delta_tilt_deg','delta_cio_dB','delta_hom_dB','delta_ttt_ms','es_action'});
end
