function [eligible, excluded, postExtensionFeasibility] = build_phase12c_kpi_update_eligible_actions(executableActions, supportTable)
%BUILD_PHASE12C_KPI_UPDATE_ELIGIBLE_ACTIONS Filter Phase 11B execs after Phase 12B extension.
%
% Inputs:
%   executableActions - Phase 11B `phase11b_final_executable_actions.csv`,
%                       i.e. final_safe_action rows only.
%   supportTable      - Phase 12B `phase12b_action_state_support_audit.csv`
%                       (post-extension implementability mapping).
%
% Outputs:
%   eligible                 - subset implementable_now AND eligible module
%                              (COC/OH or LB/MLB) AND no excluded mechanism.
%   excluded                 - every other row with an exclusion_reason.
%   postExtensionFeasibility - full re-classification of executable rows,
%                              including non-eligible rows (for the audit
%                              CSV phase12c_post_extension_feasibility.csv).

eligibleModules = {'COC/OH','LB/MLB'};

% Re-classify every executable row using the post-Phase-12B mapping.
postExtensionFeasibility = audit_action_implementability(executableActions, supportTable);

n = height(postExtensionFeasibility);
isEligibleModule = ismember(string(postExtensionFeasibility.module_name), eligibleModules);
isImplementable = strcmp(postExtensionFeasibility.implementability_status, 'implementable_now');

% Eligible mechanism filter: actions only touching referencePowerOffset_dB
% (delta_prs_dB), electricalTilt_deg (delta_tilt_deg), and cio_dB
% (delta_cio_dB). HOM/TTT deltas must be zero; sleep flag must be absent.
deltaHom = pull_col(postExtensionFeasibility, 'delta_hom_dB');
deltaTtt = pull_col(postExtensionFeasibility, 'delta_ttt_ms');
esActions = pull_string(postExtensionFeasibility, 'es_action');
sleepFlag = pull_col(postExtensionFeasibility, 'sleep_flag');

noHomTtt = (deltaHom == 0) & (deltaTtt == 0);
noEsState = (esActions == "") | (esActions == "keep_active");
noSleepFlag = sleepFlag == 0;

eligibleMask = isEligibleModule & isImplementable & noHomTtt & noEsState & noSleepFlag;

exclusionReason = strings(n, 1);
for i = 1:n
    if eligibleMask(i)
        continue;
    end
    if ~isEligibleModule(i)
        exclusionReason(i) = sprintf('module %s not eligible (only COC/OH and LB/MLB)', ...
            postExtensionFeasibility.module_name{i});
    elseif ~isImplementable(i)
        exclusionReason(i) = sprintf('implementability_status = %s', ...
            postExtensionFeasibility.implementability_status{i});
    elseif ~noHomTtt(i)
        exclusionReason(i) = 'carries non-zero HOM/TTT delta (state placeholder only)';
    elseif ~noEsState(i)
        exclusionReason(i) = sprintf('carries ES action %s (RF/KPI hookup not implemented)', char(esActions(i)));
    elseif ~noSleepFlag(i)
        exclusionReason(i) = 'sleep_flag set; ES sleep RF impact not implemented';
    else
        exclusionReason(i) = 'unclassified non-eligible row';
    end
end

postExtensionFeasibility.eligible_for_kpi_update = eligibleMask;
postExtensionFeasibility.kpi_update_exclusion_reason = cellstr(exclusionReason);

% Build narrow eligible table.
eligibleRows = postExtensionFeasibility(eligibleMask, :);
eligible = compose_eligible_table(eligibleRows);

excludedRows = postExtensionFeasibility(~eligibleMask, :);
excluded = compose_excluded_table(excludedRows, exclusionReason(~eligibleMask));
end

function T = compose_eligible_table(rows)
if isempty(rows)
    T = build_empty_eligible();
    return;
end

n = height(rows);
T = table( ...
    rows.final_decision_id, rows.coordinator_group_id, rows.selected_action_id_safe, ...
    rows.scenario_name, rows.realization_id, rows.module_name, ...
    rows.decision_source_sector_id, rows.decision_target_sector_id, ...
    rows.source_sector_id, rows.target_sector_id, ...
    rows.coordinator_affected_sector_id, rows.application_affected_sector_id, ...
    rows.application_state_variable, ...
    rows.accepted_action_type, rows.affected_parameter, ...
    rows.delta_prs_dB, rows.delta_tilt_deg, rows.delta_cio_dB, ...
    rows.implementability_status, rows.simulator_state_variable, ...
    true(n, 1), true(n, 1), ...
    'VariableNames', {'final_decision_id','coordinator_group_id','selected_action_id_safe', ...
    'scenario_name','realization_id','module_name', ...
    'decision_source_sector_id','decision_target_sector_id', ...
    'source_sector_id','target_sector_id', ...
    'coordinator_affected_sector_id','application_affected_sector_id', ...
    'application_state_variable','action_type','affected_parameter', ...
    'delta_prs_dB','delta_tilt_deg','delta_cio_dB', ...
    'implementability_status','simulator_state_variables', ...
    'can_apply_in_phase12d','kpi_t_plus_1_not_generated_flag'});
end

function T = compose_excluded_table(rows, reasons)
if isempty(rows)
    T = build_empty_excluded();
    return;
end
T = table(rows.final_decision_id, rows.coordinator_group_id, rows.selected_action_id_safe, ...
    rows.scenario_name, rows.realization_id, rows.module_name, ...
    rows.decision_source_sector_id, rows.decision_target_sector_id, ...
    rows.source_sector_id, rows.target_sector_id, ...
    rows.coordinator_affected_sector_id, rows.application_affected_sector_id, ...
    rows.application_state_variable, ...
    rows.accepted_action_type, rows.implementability_status, ...
    cellstr(reasons), ...
    'VariableNames', {'final_decision_id','coordinator_group_id','selected_action_id_safe', ...
    'scenario_name','realization_id','module_name', ...
    'decision_source_sector_id','decision_target_sector_id', ...
    'source_sector_id','target_sector_id', ...
    'coordinator_affected_sector_id','application_affected_sector_id', ...
    'application_state_variable','action_type', ...
    'implementability_status','exclusion_reason'});
end

function v = pull_col(T, name)
if ismember(name, T.Properties.VariableNames)
    v = double(T.(name));
    v(~isfinite(v)) = 0;
else
    v = zeros(height(T), 1);
end
end

function s = pull_string(T, name)
if ismember(name, T.Properties.VariableNames)
    s = string(T.(name));
    s(ismissing(s)) = "";
else
    s = strings(height(T), 1);
end
end

function T = build_empty_eligible()
T = table('Size', [0 22], ...
    'VariableTypes', {'double','double','double','cell','double','cell', ...
    'double','double','double','double','double','double','cell', ...
    'cell','cell','double','double','double','cell','cell','logical','logical'}, ...
    'VariableNames', {'final_decision_id','coordinator_group_id','selected_action_id_safe', ...
    'scenario_name','realization_id','module_name', ...
    'decision_source_sector_id','decision_target_sector_id', ...
    'source_sector_id','target_sector_id', ...
    'coordinator_affected_sector_id','application_affected_sector_id', ...
    'application_state_variable','action_type','affected_parameter', ...
    'delta_prs_dB','delta_tilt_deg','delta_cio_dB', ...
    'implementability_status','simulator_state_variables', ...
    'can_apply_in_phase12d','kpi_t_plus_1_not_generated_flag'});
end

function T = build_empty_excluded()
T = table('Size', [0 16], ...
    'VariableTypes', {'double','double','double','cell','double','cell', ...
    'double','double','double','double','double','double','cell', ...
    'cell','cell','cell'}, ...
    'VariableNames', {'final_decision_id','coordinator_group_id','selected_action_id_safe', ...
    'scenario_name','realization_id','module_name', ...
    'decision_source_sector_id','decision_target_sector_id', ...
    'source_sector_id','target_sector_id', ...
    'coordinator_affected_sector_id','application_affected_sector_id', ...
    'application_state_variable','action_type', ...
    'implementability_status','exclusion_reason'});
end
