function [moduleSummary, scenarioSummary] = summarize_phase12d_kpi_update(resultRows)
%SUMMARIZE_PHASE12D_KPI_UPDATE Per-module and per-scenario mean delta KPIs.

moduleSummary = table();
scenarioSummary = table();
if isempty(resultRows)
    return;
end

modules = unique(string(resultRows.module_name), 'stable');
nM = numel(modules);
mRows = cell(nM, 7);
for k = 1:nM
    m = modules(k);
    mask = string(resultRows.module_name) == m;
    sub = resultRows(mask, :);
    mRows(k, :) = {char(m), height(sub), ...
        mean(sub.delta_attach_rate, 'omitnan'), ...
        mean(sub.delta_mean_rsrp_dB, 'omitnan'), ...
        mean(sub.delta_mean_sinr_dB, 'omitnan'), ...
        mean(sub.delta_mean_sector_load, 'omitnan'), ...
        mean(sub.delta_qos_satisfaction_ratio, 'omitnan')};
end
moduleSummary = cell2table(mRows, 'VariableNames', {'module_name','action_count', ...
    'mean_delta_attach_rate','mean_delta_rsrp_dB','mean_delta_sinr_dB', ...
    'mean_delta_sector_load','mean_delta_qos_satisfaction_ratio'});

scenarios = unique(string(resultRows.scenario_name), 'stable');
nS = numel(scenarios);
sRows = cell(nS, 7);
for k = 1:nS
    s = scenarios(k);
    mask = string(resultRows.scenario_name) == s;
    sub = resultRows(mask, :);
    sRows(k, :) = {char(s), height(sub), ...
        mean(sub.delta_attach_rate, 'omitnan'), ...
        mean(sub.delta_mean_rsrp_dB, 'omitnan'), ...
        mean(sub.delta_mean_sinr_dB, 'omitnan'), ...
        mean(sub.delta_mean_sector_load, 'omitnan'), ...
        mean(sub.delta_qos_satisfaction_ratio, 'omitnan')};
end
scenarioSummary = cell2table(sRows, 'VariableNames', {'scenario_name','action_count', ...
    'mean_delta_attach_rate','mean_delta_rsrp_dB','mean_delta_sinr_dB', ...
    'mean_delta_sector_load','mean_delta_qos_satisfaction_ratio'});
end
