function validationTable = validate_phase7c_tp_qp_diagnostics(cfg, inputFeatures, tpComparison, qpComparison, qpBoundedMetrics, qpBoundedPredictions, qpVarianceDiagnostic)
%VALIDATE_PHASE7C_TP_QP_DIAGNOSTICS Validate Phase 7C diagnostic outputs.

rows = {};
rows = add_check(rows, 'tp_baseline_comparison_exists', 'error', ...
    isfile(fullfile(cfg.tablesDir, 'phase7c_tp_baseline_comparison.csv')), ...
    'phase7c_tp_baseline_comparison.csv', 'TP baseline comparison table must exist.', '');
rows = add_check(rows, 'qp_baseline_comparison_exists', 'error', ...
    isfile(fullfile(cfg.tablesDir, 'phase7c_qp_baseline_comparison.csv')), ...
    'phase7c_qp_baseline_comparison.csv', 'QP baseline comparison table must exist.', '');
rows = add_check(rows, 'qp_bounded_metrics_exists', 'error', ...
    isfile(fullfile(cfg.tablesDir, 'phase7c_qp_bounded_prediction_metrics.csv')), ...
    'phase7c_qp_bounded_prediction_metrics.csv', 'QP bounded metrics table must exist.', '');
rows = add_check(rows, 'qp_target_variance_diagnostic_exists', 'error', ...
    isfile(fullfile(cfg.tablesDir, 'phase7c_qp_target_variance_diagnostic.csv')), ...
    'phase7c_qp_target_variance_diagnostic.csv', 'QP target variance diagnostic table must exist.', '');

rows = add_check(rows, 'tp_persistence_baseline_reported', 'error', ...
    any(strcmp(tpComparison.model_name, 'TP_persistence')), 'TP_persistence', ...
    'Persistence baseline must be reported for TP.', '');
rows = add_check(rows, 'qp_persistence_baseline_reported', 'error', ...
    any(strcmp(qpComparison.model_name, 'QP_persistence')), 'QP_persistence', ...
    'Persistence baseline must be reported for QP.', '');
rows = add_check(rows, 'qp_raw_and_bounded_evaluated', 'error', ...
    all(ismember({'QP_raw','QP_bounded'}, unique(qpBoundedMetrics.model_name))), ...
    strjoin(unique(qpBoundedMetrics.model_name), ', '), 'QP raw and bounded predictions must both be evaluated.', '');

boundedOk = all(qpBoundedPredictions.bounded_predicted_qos >= 0 & qpBoundedPredictions.bounded_predicted_qos <= 1);
rows = add_check(rows, 'bounded_qp_predictions_within_range', 'error', boundedOk, join_flag(boundedOk), ...
    'Bounded QP predictions must be within [0, 1].', '');

lowVarianceFlagged = any(qpVarianceDiagnostic.target_std < 0.05 & contains(qpVarianceDiagnostic.notes, 'R2 is unstable'));
rows = add_check(rows, 'low_variance_qp_cases_flagged', 'error', lowVarianceFlagged, join_flag(lowVarianceFlagged), ...
    'Scenario-wise QP low-variance cases must be flagged.', '');

forbidden = detect_forbidden(inputFeatures);
rows = add_check(rows, 'no_forbidden_features_used', 'error', isempty(forbidden), ...
    strjoin(forbidden, ', '), 'Forbidden metadata/status/power columns must not be model inputs.', '');
nextInputs = inputFeatures(startsWith(inputFeatures, 'next_'));
rows = add_check(rows, 'no_future_targets_used_as_inputs', 'error', isempty(nextInputs), ...
    strjoin(nextInputs, ', '), 'Future target columns must not be used as inputs.', '');
rows = add_check(rows, 'scenario_name_grouping_only', 'error', ~any(strcmp(inputFeatures, 'scenario_name')), ...
    join_flag(~any(strcmp(inputFeatures, 'scenario_name'))), 'scenario_name must be used only for grouped reporting.', '');

validationTable = cell2table(rows, 'VariableNames', ...
    {'check_name','severity','pass_flag','actual_value','expected_condition','notes'});
writetable(validationTable, fullfile(cfg.tablesDir, 'phase7c_tp_qp_diagnostic_validation.csv'));
end

function forbidden = detect_forbidden(inputFeatures)
hardForbidden = {'scenario_name','site_id','sector_id','temporal_sample_id','day_id', ...
    'sector_status','impaired_sector_id','impaired_site_id','impaired_sector_status', ...
    'is_impaired_sector','referencePowerOffset_dB','txPowerOffset_dB','outage_flag', ...
    'degradation_flag','cod_label'};
forbidden = unique([intersect(inputFeatures, hardForbidden), inputFeatures(startsWith(inputFeatures, 'next_'))]);
end

function rows = add_check(rows, checkName, severity, passFlag, actualValue, expectedCondition, notes)
rows(end+1, :) = {checkName, severity, logical(passFlag), actualValue, expectedCondition, notes}; %#ok<AGROW>
end

function value = join_flag(flag)
if flag
    value = 'true';
else
    value = 'false';
end
end
