function sanityTable = validate_phase3_scenarios(cfg, scenarioSummary)
%VALIDATE_PHASE3_SCENARIOS Check whether Phase 3 scenarios are distinct.
%
% These checks are simulation sanity checks, not ML validation metrics.

rows = {};

normal = get_scenario_row(scenarioSummary, 'normal');
lowLoad = get_scenario_row(scenarioSummary, 'low_load');
overload = get_scenario_row(scenarioSummary, 'overload');
outage = get_scenario_row(scenarioSummary, 'outage_sector');
mixed = get_scenario_row(scenarioSummary, 'mixed_conflict');
handover = get_scenario_row(scenarioSummary, 'handover_stress');
esCandidate = get_scenario_row(scenarioSummary, 'low_load_energy_saving_candidate');

rows = add_check(rows, 'low_load_mean_load_below_normal', ...
    'low_load mean load < normal mean load', ...
    lowLoad.mean_sector_load, normal.mean_sector_load, ...
    lowLoad.mean_sector_load < normal.mean_sector_load, '');

rows = add_check(rows, 'normal_qos_above_overload', ...
    'normal QoS > overload QoS', ...
    normal.qos_satisfaction_ratio_active, overload.qos_satisfaction_ratio_active, ...
    normal.qos_satisfaction_ratio_active > overload.qos_satisfaction_ratio_active, '');

rows = add_check(rows, 'overload_count_above_normal', ...
    'overload overloaded sectors > normal overloaded sectors', ...
    overload.overloaded_sector_count, normal.overloaded_sector_count, ...
    overload.overloaded_sector_count > normal.overloaded_sector_count, '');

hasHeavyCollapse = any(strcmp(scenarioSummary.scenario_name, 'heavy_overload')) || ...
    any(strcmp(scenarioSummary.traffic_mode, 'heavy_overload'));
rows = add_check(rows, 'no_heavy_collapse_scenario', ...
    'heavy/full collapse is not part of Phase 3', ...
    double(hasHeavyCollapse), 0, ~hasHeavyCollapse, ...
    'Phase 3 should not include heavy_overload unless explicitly requested.');

rows = add_check(rows, 'outage_attach_not_above_normal', ...
    'outage_sector attach rate <= normal attach rate', ...
    outage.attach_rate, normal.attach_rate, ...
    outage.attach_rate <= normal.attach_rate, '');

rows = add_check(rows, 'mixed_overload_close_to_overload', ...
    'mixed_conflict overloaded sectors >= overload overloaded sectors - 1', ...
    mixed.overloaded_sector_count, overload.overloaded_sector_count, ...
    mixed.overloaded_sector_count >= overload.overloaded_sector_count - 1, ...
    'Allows one-sector tolerance because impairment may move UEs or traffic.');

rows = add_check(rows, 'handover_risk_above_normal', ...
    'handover_stress risk score > normal risk score', ...
    handover.handover_risk_score, normal.handover_risk_score, ...
    handover.handover_risk_score > normal.handover_risk_score, '');

rows = add_check(rows, 'handover_boundary_ratio_above_normal', ...
    'handover_stress boundary UE ratio > normal boundary UE ratio', ...
    handover.boundary_ue_ratio, normal.boundary_ue_ratio, ...
    handover.boundary_ue_ratio > normal.boundary_ue_ratio, '');

rows = add_check(rows, 'energy_saving_candidates_exist', ...
    'low_load_energy_saving_candidate ES candidate sector count > 0', ...
    esCandidate.es_candidate_sector_count, 0, ...
    esCandidate.es_candidate_sector_count > 0, '');

sanityTable = cell2table(rows, 'VariableNames', ...
    {'check_name','expected_condition','actual_value','reference_value','pass_flag','notes'});

writetable(sanityTable, fullfile(cfg.tablesDir, 'phase3_scenario_sanity_check.csv'));
end

function row = get_scenario_row(scenarioSummary, scenarioName)
idx = strcmp(scenarioSummary.scenario_name, scenarioName);
if ~any(idx)
    error('Missing scenario in Phase 3 summary: %s', scenarioName);
end
row = scenarioSummary(find(idx, 1), :);
end

function rows = add_check(rows, checkName, expectedCondition, actualValue, referenceValue, passFlag, notes)
rows(end+1, :) = {checkName, expectedCondition, actualValue, referenceValue, logical(passFlag), notes}; %#ok<AGROW>
end
