function sleepReport = build_vendor_es_sleep_report(esTable, vcfg)
%BUILD_VENDOR_ES_SLEEP_REPORT Extract consecutive ES sleep candidate windows.

if isempty(esTable)
    sleepReport = table();
    return;
end

sleepRows = esTable(strcmp(string(esTable.es_decision), 'sleep_candidate_manual_review'), :);
if isempty(sleepRows)
    sleepReport = empty_sleep_table();
    return;
end

sleepRows = sortrows(sleepRows, {'sim_sector_id','timestamp'});
rows = cell(height(sleepRows), 16);
rowIdx = 0;
sectors = unique(sleepRows.sim_sector_id);

for s = sectors(:)'
    S = sleepRows(sleepRows.sim_sector_id == s, :);
    idx = (1:height(S))';
    breakMask = minutes(S.timestamp(idx(2:end)) - S.timestamp(idx(1:end-1))) > ...
        vcfg.expectedGranularityMinutes;
    starts = idx([true; breakMask]);
    ends = idx([breakMask; true]);
    for k = 1:numel(starts)
        G = S(starts(k):ends(k), :);
        rowIdx = rowIdx + 1;
        rows(rowIdx, :) = {G.affected_sector{1}, G.sim_sector_id(1), G.cell_uid{1}, ...
            G.cell_id(1), G.display_cell{1}, G.timestamp(1), G.timestamp(end), ...
            height(G), height(G) * vcfg.expectedGranularityMinutes, ...
            max(G.predicted_dl_prb_utilization_1h, [], 'omitnan'), ...
            max(G.predicted_active_users_1h, [], 'omitnan'), ...
            max(G.predicted_traffic_volume_dl_kbyte_1h, [], 'omitnan'), ...
            min(G.min_neighbor_predicted_dl_prb, [], 'omitnan'), ...
            'manual_sleep_review_only', ...
            sprintf('%s is an ES sleep candidate from %s to %s for %d minutes; advisory only, no sleep applied.', ...
            G.display_cell{1}, datestr(G.timestamp(1), 'dd-mmm HH:MM'), ...
            datestr(G.timestamp(end), 'dd-mmm HH:MM'), height(G) * vcfg.expectedGranularityMinutes), ...
            'Advisory only: no real sleep action applied'};
    end
end

sleepReport = cell2table(rows(1:rowIdx, :), 'VariableNames', sleep_columns());
sleepReport = sortrows(sleepReport, {'duration_minutes','max_predicted_dl_prb'}, {'descend','ascend'});
end

function T = empty_sleep_table()
T = table('Size', [0 numel(sleep_columns())], ...
    'VariableTypes', {'cell','double','cell','double','cell','datetime','datetime', ...
    'double','double','double','double','double','double','cell','cell','cell'}, ...
    'VariableNames', sleep_columns());
end

function names = sleep_columns()
names = {'affected_sector','sim_sector_id','cell_uid','cell_id','display_cell', ...
    'first_timestamp','last_timestamp','candidate_event_count','duration_minutes', ...
    'max_predicted_dl_prb','max_predicted_active_users', ...
    'max_predicted_traffic_volume_dl_kbyte','min_neighbor_predicted_dl_prb', ...
    'recommended_es_action','proof_summary','claim_boundary'};
end
