function [simpleActions, simpleSummary] = build_vendor_coc_ml_readable_report(selectedActions)
%BUILD_VENDOR_COC_ML_READABLE_REPORT Make compact COC ML advisory reports.
%
% The raw ML table is intentionally detailed for audit. These reports are
% for engineering review: what happened, what is suggested, and whether it
% is safe enough for manual review.

simpleActions = table();
simpleSummary = table();
if isempty(selectedActions)
    return;
end

n = height(selectedActions);
affectedSector = compose('S%d', selectedActions.source_sim_sector_id);
affectedCell = strcat(string(selectedActions.source_vendor_site_key), "_", ...
    compose('%02d', selectedActions.source_cell_id));

targetSector = repmat("none", n, 1);
hasTarget = isfinite(selectedActions.target_sim_sector_id);
targetSector(hasTarget) = compose('S%d', selectedActions.target_sim_sector_id(hasTarget));

targetSite = string(selectedActions.target_vendor_site_key);
targetSite(targetSite == "" | ismissing(targetSite)) = "none";

decision = strings(n, 1);
actionText = strings(n, 1);
for i = 1:n
    if logical(selectedActions.is_no_op(i))
        decision(i) = "No COC action";
        actionText(i) = "No RF parameter change";
    elseif ismember(string(selectedActions.ml_safety_status{i}), ...
            ["candidate_for_manual_review", "site_outage_coc_ml_advisory"])
        decision(i) = "COC ML compensation advisory";
        actionText(i) = compose("Target %s: %+g dB RS, %+g deg eTilt", ...
            targetSector(i), selectedActions.delta_prs_dB(i), selectedActions.delta_tilt_deg(i));
    elseif string(selectedActions.ml_safety_status{i}) == "conditional_after_alarm_power_backhaul_check" || ...
            string(selectedActions.ml_safety_status{i}) == "conditional_site_incident_check_first"
        decision(i) = "COC conditional review";
        actionText(i) = compose("Target %s: %+g dB RS, %+g deg eTilt", ...
            targetSector(i), selectedActions.delta_prs_dB(i), selectedActions.delta_tilt_deg(i));
    else
        decision(i) = "Engineer review";
        actionText(i) = string(selectedActions.parameter_suggestion{i});
    end
end

simpleActions = table( ...
    selectedActions.timestamp, ...
    string(selectedActions.source_vendor_site_key), ...
    affectedSector, ...
    affectedCell, ...
    string(selectedActions.cod_state), ...
    string(selectedActions.cod_reason), ...
    decision, ...
    targetSite, ...
    targetSector, ...
    actionText, ...
    selectedActions.delta_prs_dB, ...
    selectedActions.delta_tilt_deg, ...
    selectedActions.predicted_reward, ...
    string(selectedActions.ml_safety_status), ...
    string(selectedActions.engineering_selection_note), ...
    repmat("Advisory only: simulation-trained ML estimate, no real action applied", n, 1), ...
    'VariableNames', {'timestamp','affected_site','affected_sector','affected_cell', ...
    'cod_state','cod_evidence','decision','target_site','target_sector', ...
    'suggested_action','rs_power_delta_db','etilt_delta_deg', ...
    'ml_predicted_reward','safety_status','engineering_note','claim_boundary'});

simpleSummary = build_grouped_summary(simpleActions);
end

function summary = build_grouped_summary(actions)
[groups, affectedSite, affectedSector, decision, targetSite, targetSector, suggestedAction, safetyStatus] = findgroups( ...
    actions.affected_site, actions.affected_sector, actions.decision, ...
    actions.target_site, actions.target_sector, actions.suggested_action, actions.safety_status);

eventCount = splitapply(@numel, actions.timestamp, groups);
startTime = splitapply(@min, actions.timestamp, groups);
endTime = splitapply(@max, actions.timestamp, groups);
meanPredictedReward = splitapply(@(x) mean(x, 'omitnan'), actions.ml_predicted_reward, groups);
maxPredictedReward = splitapply(@(x) max(x, [], 'omitnan'), actions.ml_predicted_reward, groups);

summary = table(affectedSite, affectedSector, decision, targetSite, targetSector, ...
    suggestedAction, safetyStatus, eventCount, startTime, endTime, ...
    meanPredictedReward, maxPredictedReward, ...
    'VariableNames', {'affected_site','affected_sector','decision','target_site', ...
    'target_sector','suggested_action','safety_status','event_count', ...
    'first_timestamp','last_timestamp','mean_ml_predicted_reward', ...
    'max_ml_predicted_reward'});
summary = sortrows(summary, {'event_count','affected_site','affected_sector'}, {'descend','ascend','ascend'});
end
